import { Award } from "lucide-react";

export const INITIAL_APPLICATIONS = [
  {
    id: "app-1",
    title: "Senior Frontend Engineer",
    company: "Vercel",
    source: "MatchIn Feed",
    status: "under-review",
    matchScore: 98,
    appliedDate: "2026-08-27",
    avatarLetter: "V",
    bgGradient: "linear-gradient(135deg, #1F365C, #3B557D)",
  },
  {
    id: "app-2",
    title: "Lead Frontend Architect",
    company: "Stripe",
    source: "MatchIn Feed",
    status: "interview",
    matchScore: 95,
    appliedDate: "2026-09-02",
    avatarLetter: "S",
    bgGradient: "linear-gradient(135deg, #635BFF, #3B31D6)",
  },
  {
    id: "app-3",
    title: "Frontend Developer (UI/UX)",
    company: "Figma Partner Studio",
    source: "LinkedIn",
    status: "offer",
    matchScore: 92,
    appliedDate: "2026-09-05",
    avatarLetter: "F",
    bgGradient: "linear-gradient(135deg, #8B5CF6, #5B21B6)",
  },
  {
    id: "app-4",
    title: "Frontend Infra Engineer",
    company: "CloudScale Systems",
    source: "MatchIn Feed",
    status: "applied",
    matchScore: 88,
    appliedDate: "2026-09-08",
    avatarLetter: "C",
    bgGradient: "linear-gradient(135deg, #0EA5A5, #0B7D7D)",
  },
  {
    id: "app-5",
    title: "Full Stack Engineer",
    company: "FinEdge Solutions",
    source: "Referral",
    status: "assessment",
    matchScore: 80,
    appliedDate: "2026-08-29",
    avatarLetter: "F",
    bgGradient: "linear-gradient(135deg, #9C432A, #C86A4C)",
  },
  {
    id: "app-6",
    title: "Backend Engineer",
    company: "PulseHealth",
    source: "MatchIn Feed",
    status: "rejected",
    matchScore: 61,
    appliedDate: "2026-07-22",
    avatarLetter: "P",
    bgGradient: "linear-gradient(135deg, #94A0AE, #68707D)",
  },
  {
    id: "app-7",
    title: "Junior Frontend Developer",
    company: "TechNova",
    source: "MatchIn Feed",
    status: "withdrawn",
    matchScore: 72,
    appliedDate: "2026-06-20",
    avatarLetter: "T",
    bgGradient: "#FAF8F4",
  },
];

export const STATUS_CONFIG = {
  all: { label: "All", color: "bg-primary/10 text-primary", dot: "bg-primary" },
  applied: {
    label: "Applied",
    color: "bg-slate-100 text-slate-700 border border-slate-200",
    dot: "bg-slate-500",
  },
  "under-review": {
    label: "Under Review",
    color: "bg-blue-50 text-primary",
    dot: "bg-primary",
  },
  interview: {
    label: "Interview",
    color: "bg-amber-50 text-warning",
    dot: "bg-warning",
  },
  assessment: {
    label: "Assessment",
    color: "bg-orange-50 text-[#9C432A]",
    dot: "bg-[#9C432A]",
  },
  offer: {
    label: "Offer",
    color: "bg-emerald-50 text-success",
    dot: "bg-success",
    icon: Award,
  },
  rejected: {
    label: "Rejected",
    color: "bg-rose-50 text-[#B3271E]",
    dot: "bg-[#B3271E]",
  },
  withdrawn: {
    label: "Withdrawn",
    color: "bg-stone-100 text-stone-500 border border-stone-200",
    dot: "bg-stone-400",
  },
};
