export const JOB_CATEGORIES = [
  { value: "all", label: "All Roles" },
  { value: "frontend", label: "Frontend" },
  { value: "fullstack", label: "Backend & Fullstack" },
  { value: "uiux", label: "UI/UX Design" },
  { value: "data-ai", label: "Data & AI" },
  { value: "remote", label: "Remote" },
];

export const JOBS = [
  {
    id: "vercel-senior-frontend",
    company: "Vercel Partner",
    initial: "V",
    logoClass: "bg-primary/10 text-primary",
    verified: true,
    location: "Remote",
    locationIcon: "globe",
    matchPercent: 98,
    title: "Senior Frontend Engineer (React / Next.js)",
    salaryRange: "$145,000 - $175,000",
    tags: ["React", "TypeScript", "Tailwind CSS", "Next.js 14"],
    postedAgo: "Posted 2h ago",
    categories: ["frontend", "remote"],
  },
  {
    id: "stripe-lead-architect",
    company: "Stripe Infrastructure",
    initial: "S",
    logoClass: "bg-secondary/10 text-secondary",
    verified: true,
    location: "San Francisco / Hybrid",
    locationIcon: "pin",
    matchPercent: 95,
    title: "Lead Frontend Architect",
    salaryRange: "$180,000 - $220,000",
    tags: ["Design Systems", "Performance", "TypeScript"],
    postedAgo: "Posted 5h ago",
    categories: ["frontend"],
  },
  {
    id: "figma-frontend-uiux",
    company: "Figma Partner Studio",
    initial: "F",
    logoClass: "bg-accent/10 text-accent",
    verified: true,
    location: "New York / Remote",
    locationIcon: "globe",
    matchPercent: 92,
    title: "Frontend Developer (UI/UX Engineering)",
    salaryRange: "$130,000 - $155,000",
    tags: ["CSS Architecture", "Vue.js / Nuxt", "Figma Tokens"],
    postedAgo: "Posted 1d ago",
    categories: ["frontend", "uiux", "remote"],
  },
  {
    id: "supabase-fullstack",
    company: "Supabase Cloud",
    initial: "S",
    logoClass: "bg-success/10 text-success",
    verified: true,
    location: "Remote",
    locationIcon: "globe",
    matchPercent: 94,
    title: "Full Stack Engineer (Frontend Heavy)",
    salaryRange: "$140,000 - $170,000",
    tags: ["React", "Node.js", "PostgreSQL"],
    postedAgo: "Posted 1d ago",
    categories: ["fullstack", "remote"],
  },
  {
    id: "retool-mobile-web",
    company: "Retool Core",
    initial: "R",
    logoClass: "bg-secondary/10 text-secondary",
    verified: true,
    location: "Hybrid",
    locationIcon: "pin",
    matchPercent: 91,
    title: "Mobile & Web Frontend Engineer",
    salaryRange: "$150,000 - $180,000",
    tags: ["React Native", "TypeScript", "Component Libraries"],
    postedAgo: "Posted 2d ago",
    categories: ["frontend"],
  },
  {
    id: "datadog-staff-infra",
    company: "Datadog Telemetry",
    initial: "D",
    logoClass: "bg-primary/10 text-primary",
    verified: true,
    location: "Remote / Boston",
    locationIcon: "globe",
    matchPercent: 96,
    title: "Staff Frontend Infrastructure Engineer",
    salaryRange: "$190,000 - $235,000",
    tags: ["Microfrontends", "Webpack/Vite", "CI/CD"],
    postedAgo: "Posted 3d ago",
    categories: ["frontend", "remote"],
  },
];
