export const ONBOARDING_STEP_FIELDS = [
  {
    number: 1,
    field: "jobTitle",
    navLabel: "Title",
    title: "What job title are you looking for?",
    subtitle:
      "We'll customize AI algorithms to suggest jobs most relevant to your career path.",
    inputLabel: "Target Job Title",
    placeholder: "Search for a job title...",
    suggestionsLabel: "Popular job titles in today's market:",
    suggestions: [
      "Product Manager",
      "Frontend Developer",
      "UX/UI Designer",
      "Data Engineer",
      "Digital Marketing Specialist",
    ],
  },
  {
    number: 2,
    field: "jobType",
    navLabel: "Type",
    title: "What type of job are you looking for?",
    subtitle: "Select the employment types that fit your current availability.",
    inputLabel: "Job Type",
    placeholder: "Select job type...",
    suggestionsLabel: "Popular job titles in today's market:",
    suggestions: [
      "Full-time",
      "Part-time",
      "Contract",
      "Freelance",
      "Internship",
    ],
  },
  {
    number: 3,
    field: "workStyle",
    navLabel: "Style",
    title: "What is your preferred work style?",
    subtitle: "Choose how and where you prefer to deliver your daily work.",
    inputLabel: "Work Style",
    placeholder: "Select work style...",
    suggestionsLabel: "Popular job titles in today's market:",
    suggestions: ["On-site", "Remote", "Hybrid"],
  },
  {
    number: 4,
    field: "location",
    navLabel: "Location",
    title: "Where would you like to work?",
    subtitle: "Specify your preferred target location or city.",
    inputLabel: "Location / City",
    placeholder: "Enter city or country...",
    suggestionsLabel: "Popular job titles in today's market:",
    suggestions: [
      "Cairo, Egypt",
      "Riyadh, KSA",
      "Dubai, UAE",
      "Remote Worldwide",
    ],
  },
  {
    number: 5,
    field: "experience",
    navLabel: "Experience",
    title: "What is your experience level?",
    subtitle: "Help us match you with roles that match your expertise.",
    inputLabel: "Experience Level",
    placeholder: "Select experience level...",
    suggestionsLabel: "Popular job titles in today's market:",
    suggestions: [
      "Entry Level / Junior",
      "Mid Level",
      "Senior",
      "Lead / Manager",
    ],
  },
  {
    number: 6,
    field: "goals",
    navLabel: "Goals",
    title: "What are your primary career goals?",
    subtitle: "Tell us what matters most to you in your next move.",
    inputLabel: "Primary Goal",
    placeholder: "Select or type your goal...",
    suggestionsLabel: "Popular job titles in today's market:",
    suggestions: [
      "Higher Salary",
      "Career Growth",
      "Better Work-Life Balance",
      "Learning New Tech",
    ],
  },
];
