import { Send, Eye, CalendarCheck, Award } from "lucide-react";

export const PIPELINE_STATS = [
  {
    key: "sent",
    label: "Sent",
    icon: Send,
    iconClass: "text-muted group-hover:text-primary transition-colors",
    value: 4,
    valueClass: "text-primary",
    suffix: "applied",
    suffixClass: "text-muted",
    footerLabel: "Pacing",
    footerValue: "Optimal",
  },
  {
    key: "in-review",
    label: "In Review",
    icon: Eye,
    iconClass: "text-success",
    value: 2,
    valueClass: "text-success",
    suffix: "active",
    suffixClass: "text-success",
    footerLabel: "Response time",
    footerValue: "~48 hrs",
  },
  {
    key: "interview",
    label: "Interview",
    icon: CalendarCheck,
    iconClass: "text-accent",
    value: 1,
    valueClass: "text-accent",
    suffix: "round 3",
    suffixClass: "text-accent",
    footerLabel: "Next round",
    footerValue: "Tomorrow",
  },
  {
    key: "offers",
    label: "Offers",
    icon: Award,
    iconClass: "text-muted",
    value: 0,
    valueClass: "text-muted",
    suffix: "pending",
    suffixClass: "text-muted",
    footerLabel: "Target comp",
    footerValue: "$175K+",
  },
];
