export const DEFAULT_PARSED_CV = {
  candidate_id: "khgkgky",
  user: {
    name: "Samir Salah",
    email: "samirsalah28@yahoo.com",
  },
  candidate_profile: {
    headline: "Retail Sales Executive — Customer Relations Specialist",
    bio: "Dynamic and results-driven Retail Sales Executive with over 10 years of experience in driving revenue growth, building customer relationships, and leading high-performing sales teams. Proven track record of exceeding sales targets by 30%+ consistently. Expert in visual merchandising, inventory management, and customer service excellence. Strong communicator with exceptional interpersonal skills and a passion for delivering outstanding shopping experiences.",
    phone: "50442508",
    location: "Kuwait City, Al Asimah, Kuwait",
    linkedin_url: "https://www.linkedin.com/in/samir-salah-37b560396/",
    github_url: null,
    portfolio_url: null,
  },
  educations: [
    {
      id: "edu-1",
      institution: "Suez Canal University",
      degree: "Bachelor",
      field_of_study: "Physical Education Teaching and Coaching",
      start_date: null,
      end_date: null,
      description:
        "Completed comprehensive program in Physical Education and Coaching. Developed strong leadership and communication skills through sports coaching. Gained experience in team management and motivational techniques.",
      confirmed: false,
    },
  ],
  experiences: [
    {
      id: "exp-1",
      company_name: "Best Al-Yousifi",
      job_title: "Retail Sales Executive",
      employment_type: "full-time",
      start_date: "2021-11",
      end_date: null,
      is_current: true,
      description:
        "Retail sales professional with over 10 years of experience working in both small and large-scale showrooms. Started career in sales and progressed to become a Store Manager in previous positions. Specialized in mobile phone sales and merchandising with proven track record. Consistently exceeded monthly sales targets through effective customer engagement and product knowledge. Built strong relationships with customers, ensuring high satisfaction and repeat business. Managed inventory and stock levels, coordinating with suppliers for timely product availability. Trained and supervised sales staff on product features, sales techniques, and customer service excellence. Implemented visual merchandising strategies to enhance product displays and drive sales.",
      technologies: [],
      confirmed: false,
    },
    {
      id: "exp-2",
      company_name: "Samsung Electronics",
      job_title: "Executive Sales Representative",
      employment_type: "full-time",
      start_date: "2015-11",
      end_date: "2021-11",
      is_current: false,
      description:
        "Delivered exceptional retail sales performance for Samsung mobile phones and electronics. Achieved consistent sales growth through deep product knowledge and customer-focused approach. Conducted product demonstrations and explained technical specifications to diverse customer base. Maintained up-to-date knowledge of Samsung product lines, features, and competitive positioning. Processed sales transactions efficiently using POS systems with high accuracy. Collaborated with marketing team on promotional campaigns and in-store events. Provided after-sales support and handled customer inquiries professionally. Contributed to store merchandising and product display optimization.",
      technologies: [],
      confirmed: false,
    },
  ],
  projects: [],
  certificates: [],
  languages: [
    {
      id: "lang-1",
      language: "Arabic",
      proficiency: "Native",
      confirmed: false,
    },
    {
      id: "lang-2",
      language: "English",
      proficiency: "Fluent",
      confirmed: false,
    },
  ],
  candidate_skills: [
    {
      skill_id: "152d66a3-26ca-415a-a3a1-18178a4ccf31",
      name: "Retail Sales",
      proficiency: null,
      years_of_experience: null,
      confidence: 0.95,
      confirmed: false,
      evidence: [
        {
          type: "header",
          text: "Retail Sales Executive — Customer Relations Specialist",
          source: "cv",
          section: "header",
        },
        {
          type: "summary",
          text: "Dynamic and results-driven Retail Sales Executive with over 10 years of experience in driving revenue growth,",
          source: "cv",
          section: "summary",
        },
        {
          type: "experience",
          text: "Retail Sales Executive Kuwait",
          source: "cv",
          section: "experience",
        },
        {
          type: "experience",
          text: "Retail sales professional with over 10 years of experience working in both small and large-scale showrooms",
          source: "cv",
          section: "experience",
        },
        {
          type: "experience",
          text: "Delivered exceptional retail sales performance for Samsung mobile phones and electronics",
          source: "cv",
          section: "experience",
        },
        {
          type: "skills",
          text: "Sales & Business Development:Retail Sales, B2C Sales, Upselling & Cross-selling, Sales Target Achievement,",
          source: "cv",
          section: "skills",
        },
      ],
    },
    {
      skill_id: "b6fe4a41-25f8-49a3-a6ac-c4fc8b4e2495",
      name: "Customer Service Excellence",
      proficiency: null,
      years_of_experience: null,
      confidence: 0.95,
      confirmed: false,
      evidence: [
        {
          type: "experience",
          text: "Trained and supervised sales staff on product features, sales techniques, and customer service excellence",
          source: "cv",
          section: "experience",
        },
        {
          type: "skills",
          text: "Customer Management:Customer Relationship Management (CRM), Customer Service Excellence, Com-",
          source: "cv",
          section: "skills",
        },
      ],
    },
    {
      skill_id: "780badc2-22fd-4dd1-bd12-fc2a1e8b924b",
      name: "Visual Merchandising",
      proficiency: null,
      years_of_experience: null,
      confidence: 0.95,
      confirmed: false,
      evidence: [
        {
          type: "summary",
          text: "targets by 30%+ consistently. Expert in visual merchandising, inventory management, and customer service",
          source: "cv",
          section: "summary",
        },
        {
          type: "experience",
          text: "Implemented visual merchandising strategies to enhance product displays and drive sales",
          source: "cv",
          section: "experience",
        },
        {
          type: "skills",
          text: "Operations & Management:Inventory Management, Visual Merchandising, Store Operations, Team Lead-",
          source: "cv",
          section: "skills",
        },
      ],
    },
    {
      skill_id: "34429c91-807a-4ddd-af31-b8d6724150d4",
      name: "Store Operations",
      proficiency: null,
      years_of_experience: null,
      confidence: 0.95,
      confirmed: false,
      evidence: [
        {
          type: "experience",
          text: "Team Leadership:Successfully led store operations during manager’s absence for 3 months, maintaining",
          source: "cv",
          section: "experience",
        },
        {
          type: "skills",
          text: "Operations & Management:Inventory Management, Visual Merchandising, Store Operations, Team Lead-",
          source: "cv",
          section: "skills",
        },
      ],
    },
    {
      skill_id: "07b50a5b-7c21-4b99-81f7-ac7daeb7841a",
      name: "POS Systems",
      proficiency: null,
      years_of_experience: null,
      confidence: 0.95,
      confirmed: false,
      evidence: [
        {
          type: "experience",
          text: "Processed sales transactions efficiently using POS systems with high accuracy",
          source: "cv",
          section: "experience",
        },
        {
          type: "skills",
          text: "Technical Skills:MS Office Suite, POS Systems, SAP Retail, CRM Software (Salesforce), Data Analysis &",
          source: "cv",
          section: "skills",
        },
      ],
    },
    {
      skill_id: "3408b8e5-d68c-4322-88f0-1a64b6fd3dc9",
      name: "Team Leadership",
      proficiency: null,
      years_of_experience: null,
      confidence: 0.8,
      confirmed: false,
      evidence: [
        {
          type: "experience",
          text: "Team Leadership:Successfully led store operations during manager’s absence for 3 months, maintaining",
          source: "cv",
          section: "experience",
        },
      ],
    },
    {
      skill_id: "209d3c55-8e9d-4bac-b988-4bf693f05312",
      name: "Inventory Management",
      proficiency: null,
      years_of_experience: null,
      confidence: 0.65,
      confirmed: false,
      evidence: [
        {
          type: "summary",
          text: "targets by 30%+ consistently. Expert in visual merchandising, inventory management, and customer service",
          source: "cv",
          section: "summary",
        },
        {
          type: "skills",
          text: "Operations & Management:Inventory Management, Visual Merchandising, Store Operations, Team Lead-",
          source: "cv",
          section: "skills",
        },
      ],
    },
    {
      skill_id: "a8197b50-4a5a-46b4-94e4-56238707c0b9",
      name: "B2C Sales",
      proficiency: null,
      years_of_experience: null,
      confidence: 0.6,
      confirmed: false,
      evidence: [
        {
          type: "skills",
          text: "Sales & Business Development:Retail Sales, B2C Sales, Upselling & Cross-selling, Sales Target Achievement,",
          source: "cv",
          section: "skills",
        },
      ],
    },
    {
      skill_id: "77b06e04-031a-42c1-aecc-f51f3d919ac0",
      name: "Upselling & Cross-selling",
      proficiency: null,
      years_of_experience: null,
      confidence: 0.6,
      confirmed: false,
      evidence: [
        {
          type: "skills",
          text: "Sales & Business Development:Retail Sales, B2C Sales, Upselling & Cross-selling, Sales Target Achievement,",
          source: "cv",
          section: "skills",
        },
      ],
    },
    {
      skill_id: "069c9d85-8105-47c2-b884-4fdfc2ecf906",
      name: "Sales Target Achievement",
      proficiency: null,
      years_of_experience: null,
      confidence: 0.6,
      confirmed: false,
      evidence: [
        {
          type: "skills",
          text: "Sales & Business Development:Retail Sales, B2C Sales, Upselling & Cross-selling, Sales Target Achievement,",
          source: "cv",
          section: "skills",
        },
      ],
    },
    {
      skill_id: "527de93c-23e1-4a55-9cd0-082ed400b452",
      name: "Lead Generation",
      proficiency: null,
      years_of_experience: null,
      confidence: 0.6,
      confirmed: false,
      evidence: [
        {
          type: "skills",
          text: "Lead Generation",
          source: "cv",
          section: "skills",
        },
      ],
    },
    {
      skill_id: "4f251e8d-2f15-45a4-b3b2-beaab7da1712",
      name: "Customer Relationship Management",
      proficiency: null,
      years_of_experience: null,
      confidence: 0.6,
      confirmed: false,
      evidence: [
        {
          type: "skills",
          text: "Customer Management:Customer Relationship Management (CRM), Customer Service Excellence, Com-",
          source: "cv",
          section: "skills",
        },
      ],
    },
    {
      skill_id: "572dbc77-a3a8-4602-8ccb-45662f2a13b9",
      name: "Client Retention",
      proficiency: null,
      years_of_experience: null,
      confidence: 0.6,
      confirmed: false,
      evidence: [
        {
          type: "skills",
          text: "plaint Resolution, Client Retention",
          source: "cv",
          section: "skills",
        },
      ],
    },
    {
      skill_id: "7d22c248-ecd1-4fc9-be15-c49a604423bd",
      name: "Staff Training & Development",
      proficiency: null,
      years_of_experience: null,
      confidence: 0.6,
      confirmed: false,
      evidence: [
        {
          type: "skills",
          text: "ership, Staff Training & Development",
          source: "cv",
          section: "skills",
        },
      ],
    },
    {
      skill_id: "a54a5af3-6abb-430f-bda1-4f4d008086ee",
      name: "MS Office Suite",
      proficiency: null,
      years_of_experience: null,
      confidence: 0.6,
      confirmed: false,
      evidence: [
        {
          type: "skills",
          text: "Technical Skills:MS Office Suite, POS Systems, SAP Retail, CRM Software (Salesforce), Data Analysis &",
          source: "cv",
          section: "skills",
        },
      ],
    },
    {
      skill_id: "a23e75a9-5897-4632-8bfa-c9d1c65cbab4",
      name: "SAP Retail",
      proficiency: null,
      years_of_experience: null,
      confidence: 0.6,
      confirmed: false,
      evidence: [
        {
          type: "skills",
          text: "Technical Skills:MS Office Suite, POS Systems, SAP Retail, CRM Software (Salesforce), Data Analysis &",
          source: "cv",
          section: "skills",
        },
      ],
    },
    {
      skill_id: "a61484a5-1e2d-4178-b10d-0a3f289088dd",
      name: "CRM Software (Salesforce)",
      proficiency: null,
      years_of_experience: null,
      confidence: 0.6,
      confirmed: false,
      evidence: [
        {
          type: "skills",
          text: "Technical Skills:MS Office Suite, POS Systems, SAP Retail, CRM Software (Salesforce), Data Analysis &",
          source: "cv",
          section: "skills",
        },
      ],
    },
  ],
  target_roles: [],
  preferences: {
    employment_type: [],
    work_mode: [],
    locations: [],
    industries: [],
  },
};
