export const MOCK_NOTIFICATIONS = [
  {
    id: "n1",
    type: "job",
    group: "TODAY",
    title: "New match for you",
    description: "Lead Frontend Architect at Stripe — 95% match, based on your target role.",
    time: "Today · 9:12 AM",
    read: false,
  },
  {
    id: "n2",
    type: "application",
    group: "TODAY",
    title: "Application status updated",
    description: "Your application for Senior Frontend Engineer at Vercel moved to In Review.",
    time: "Today · 8:04 AM",
    read: false,
  },
  {
    id: "n3",
    type: "cv",
    group: "TODAY",
    title: "CV analysis complete",
    description: "We found 14 skills in resume_2026.pdf — 9 matched, 3 flagged as growth areas.",
    time: "Today · 7:41 AM",
    read: true,
  },
  {
    id: "n4",
    type: "roadmap",
    group: "EARLIER",
    title: "Roadmap reminder",
    description: "One task left in Phase 1: Foundations — you're 75% through this phase.",
    time: "Yesterday · 6:00 PM",
    read: true,
  },
  {
    id: "n5",
    type: "platform",
    group: "EARLIER",
    title: "Confirm your email",
    description: "Please verify your email address to keep receiving application updates.",
    time: "Sep 5 · 11:20 AM",
    read: true,
  },
  {
    id: "n6",
    type: "application",
    group: "EARLIER",
    title: "Application received",
    description: "Your application for Senior Frontend Engineer at Vercel was submitted.",
    time: "Sep 4 · 2:15 PM",
    read: true,
  },
];
